blog_auth/urls.py
from django.urls import path
from django.views.generic import TemplateView
from django.contrib.auth import views as auth_views
from .views import SignUpView

app_name= 'blog_auth'

urlpatterns = [
    path('login', auth_views.LoginView.as_view(),name='login'),
    path('logout', auth_views.LogoutView.as_view(),name='logout'),
    path('register', SignUpView.as_view(),name='register'),
    path('registercomplete', TemplateView.as_view(template_name='registration/registercomplete.html'),name='registercomplete'),
]

blogapp/urls.py
from django.contrib import admin
from django.urls import include,path
from django.urls import re_path
from django.conf.urls.static import static
from django.conf import settings
from blogapp import views

urlpatterns = [
    path('noticias/<int:id>/', views.noticiasdetalle, name='noticiasdetalle'),
    path('comentario/<int:id>/approve', views.comment_approve, name='comment_approve'),
    path('comentario/<int:id>/remove', views.comment_remove, name='comment_remove'),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT, show_indexes=True)

somosbarro/urls.py
from django.contrib import admin
from blogapp import views
from django.conf.urls.static import static
from django.conf import settings
from django.urls import include,path
from django.urls import re_path as url

urlpatterns = [
    path('',views.index, name = 'index'),
    path('quienessomos/',views.quienessomos, name = 'quienessomos'),
    path('Contactanos/',views.contactanos, name = 'contactanos'),
    path('publicaciones/',views.publicaciones, name = 'publicaciones'),
    path('admin/', admin.site.urls),
    url('noticias/', include('blogapp.urls')),
    path('registration/', include('blog_auth.urls')),
] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT, show_indexes=True)

somosbarro/templates/Contactanos.html
{% extends 'base.html'%}
{% load static %}

{% block contenido %}
    <!--Icon-Font-->
    <script src="https://kit.fontawesome.com/eb496ab1a0.js" crossorigin="anonymous"></script>
<!--</head>-->
<!--<body>-->
    <div class="container-form">
        <div class="info-form">
            <h1>Contáctanos</h1>
            <p>¿Querés colaborar con nosotros?, ¿Tenés sugerencias o propuestas?, ¿Te gusta lo que ves y querés dejar tu aporte?.</p>
            <a href="#"><i class="fa fa-phone"></i> 0362 471-4588 </a>
            <a href="#"><i class="fa fa-envelope"></i> somosbarro@gmail.com</a>
            <a href="https://www.google.com.ar/maps/place/Sta+Mar%C3%ADa+de+Oro+2685,+Resistencia,+Chaco/@-27.4717682,-59.0134895,17z/data=!3m1!4b1!4m5!3m4!1s0x94450c9fcabdae89:0x46bf48b7e961372c!8m2!3d-27.471773!4d-59.0113008"><i class="fa fa-map-marked"></i> Santa Maria de Oro 2685, Resistencia, Argentina</a>
            <a href="https://www.facebook.com/fundacionsomosbarro"><i class="fa fa-facebook"></i> Fundacion Somos Barro </a>
            <a href="https://www.instagram.com/fundacionsomosbarro/"><i class="fa fa-instagram"></i> fundacionsomosbarro </a>
        </div>
        <form action="#" autocomplete="off">
            <input type="text" name="nombre" placeholder="Tu Nombre" class="campo">
            <input type="emal" name="email" placeholder="Tu Email" class="campo">
            <textarea name="mensaje" placeholder="Tu Mensaje..."></textarea>
            <input type="submit" name="enviar" value="Enviar Mensaje" class="btn-enviar">
        </form>
    </div>
</body>
{% endblock %}

somosbarro/templates/base.html
<!DOCTYPE html>
{% load static %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!--Bootstrap-->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.2/font/bootstrap-icons.css">

    <!--Font-->
    <link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=Inter:wght@200&family=Montserrat:wght@300;400;700&family=Open+Sans:wght@300;400;700&display=swap" rel="stylesheet">
    <!--Links CSS-->
    <link rel="stylesheet" href="{% static 'css/reset.css'%}">
    <link rel="stylesheet" href="{% static 'css/header.css'%}">
    <link rel="stylesheet" href="{% static 'css/novedades.css'%}">
    <link rel="stylesheet" href="{% static 'css/publicaciones.css'%}">
    <link rel="stylesheet" href="{% static 'css/contacto.css'%}">
    <link rel="stylesheet" href="{% static 'css/contacto2.css'%}">
    <link rel="stylesheet" href="{% static 'css/footer.css'%}">

    <title>Somos Barro</title>
    <link rel="shortcut icon" href="{% static 'iconos/favicon.ico'%}">
</head>

<body>
 <!--Navegacion-->
    <header class="header">
        <nav class="navbar navbar-expand-lg light">
            <div class="container-fluid">
            <a class="navbar-brand" href="#"> 
                <img src="{% static 'img/Fundacion_Somos_Barro_Logo.jpg'%}" width="50px" alt="logosomosbarro">
            </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            </div>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="barra navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'index'%}">Inicio</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'quienessomos'%}">¿Quienes Somos?</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'publicaciones'%}">Noticias</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'contactanos'%}">Contactanos</a>
                </li>
                </ul>
            </nav>
            </div>
        

            <div class="botones">
                <div class="buscador">
                    <form class="d-flex" role="search">
                    <input class=" buscador form-control me-2" type="search" placeholder="Buscar" aria-label="Search">
                    <button class="btn btn-outline-success" type="submit">Buscar</button>
                </form>
                </div>
                {% if user.is_authenticated %}
                    <h3><b>Hola {{ user.username }}</b></h3>
                    <a class="btn btn-success" href="{%url 'blog_auth:logout'%}">Cerrar Sesión</a>
                {% else %}
                <div class="botones__acceso">
                    <a class="btn btn-success" href="{%url 'blog_auth:login'%}">Acceder</a>
                    <!--<button type="button" class="btn btn-primary">Acceder</button>
                    <button type="button" class="btn btn-primary">Registrarse</button>-->
                    <a class="btn btn-primary" href="{%url 'blog_auth:register'%}">Registrarse</a>
                </div>
               
                {% endif %}
            </div>
    </header>

    <!--seccion presentacion rapida-->
    <main>
        {% block contenido %}
        {% endblock %}

<!--Footer-->

<footer class="footer_container">
    <div>
      <span class="texto_footer">© 2022, Somos Barro</span>
    </div>

    <div class="iconos_footer">
        <div class="imagen_footer">
            <!--<a href="https://www.facebook.com/Somos-barro-459659007945458/">-->
            <a href="https://www.facebook.com/fundacionsomosbarro">
                <img class="imagen_redes__footer" src="{% static 'img/redes/facebook.svg'%}" alt="facebook">
            </a>
        </div>

        <div class="imagen_footer">
            <a href="https://www.instagram.com/fundacionsomosbarro/?igshid=YmMyMTA2M2Y%3D">
                <img class="imagen_redes__footer" src="{% static 'img/redes/instagram.svg'%}" alt="instagram">
                
              </a>
        </div>
    </div>
  </footer>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
</body>
</html>

somosbarro/templates/detalle-noticia.html
{% extends 'base.html' %}
{% load static %}

{% block contenido %}
    <article class="row mt-5">
        <h1> {{ noticia.titulo}} </h1>

        <div class="date"> {{ noticia.creado }}</div>
        <div class="col-md-5">
            <img src="{{ noticia.img.url }}" width="100%" alt="">
        </div>
        <p>
        {{ noticia.contenido|safe|linebreaksbr}}
        </p>
      

        <hr>
        {% if user.is_authenticated%}
            <h3>Escribe un comentario</h3>
            <form method="post" style="margin-top: 1.3em;">
            {% csrf_token %}
            {{ comentario_form.as_p }}

            <button type="submit" class="btn btn-primary  btn-lg">Enviar comentario</button>
            </form>
        {% else %}
        <p>Para agregar comentarios debe autenticarse <br>
            <a href="{% url 'blog_auth:login' %}">Iniciar sesión</a>
            <a href="{% url 'blog_auth:register' %}">Registrarse</a></p>
        {% endif %}
        <hr>
        <div class="container">
            {% for comentario in noticia.comentarios.all %}
                <br>
                {% if user.is_authenticated or comment.approved_comment %}

                    {{ comentario.creado }}
                    {% if not comment.approved_comment %}
                        <a class="btn btn-default" href="{% url 'comment_remove' id=comentario.id %}"><span class="glyphicon glyphicon-remove"></span></a>
                        <a class="btn btn-default" href="{% url 'comment_approve' id=comentario.id %}"><span class="glyphicon glyphicon-ok"></span></a>
                    {% endif %}
                    <p>{{ comentario.cuerpo_comentario|safe|linebreaks }}</p>
                    <p>Posted by: <strong>{{ comentario.autor }}</strong></p>
                {% endif %}
                {% empty %}
                <p>No hay comentarios.</p>
            {% endfor %}
        </div>
    </article>
    
{% endblock %}

somosbarro/templates/index.html
{% extends 'base.html'%}
{% load static %}

{% block contenido %}

        <section class="presentacion">
            <div class="presentacion_texto">
                <h1 class="texto">Fundación Somos Barro</h1>
                <h2>Nuestro principal objetivo es construinos colectivamente a través del Arte, promoviendo políticas de inclusión, ampliando el acceso a la educación.</h2>
            </div>

            <div class="presentacion_imagen">
                <img src="{% static 'img/presentacionimagen.svg'%}" alt="imagen" class="imagen-presentacion"> 
                
            </div>


        </section>

       
     <!--seccion publicaciones-->
        
        <section class="publicaciones">
            <h2 class="titulo__publicaciones">Publicaciones</h2>

            <div class=" tarjetas row row-cols-1 row-cols-md-3 g-4">
              {% for noticia in noticiasdestacadas%}
                <div class="col">
                  <div class="card h-100">
                    <img src="{{ noticia.img.url }}" width="300" alt="" class="card-img-top">
                    <!--<img src="media/img/noticias/img" width="500" alt="" class="card-img-top">-->
                    <div class="card-body">
                      <h5 class="card-title">{{ noticia.titulo }}</h5>
                      <p class="card-text">{{ noticia.contenido }}.</p>
                    </div>
                    <div class="card-footer">
                      <small class="text-muted">Publicado: {{ noticia.publicado }}</small>
                      <p><a class="btn btn-secondary" href="{% url 'noticiasdetalle' id=noticia.id %}">Leer más &raquo;</a></p>
                    </div>
                  </div>
                </div>
              {% endfor%}
            </div>
        </section>



    <!--Contacto-->
        <section class="seccion_contacto">
            <h2 class="titulo__contacto">Contacto</h2>

            <div class="redes_sociales">
                
                <div class="redes_iconos">
                    <div>
                        <a href="#">
                            <img class="imagen" src="static/img/redes/whatsapp.svg" alt="Whatsapp">
                            <p class="texto_icono">3624313131</p>
                          </a>
                    </div>
                  
                    <div>
                        <a href="#">
                            <img class="imagen" src="static/img/redes/envelope-at.svg" alt="Mail">
                            <p class="texto_icono">somosbarro@gmail.com</p>
                        </a>
                    </div>
                  

                    <div>
                
                        <a href="#">
                            <img class="imagen" src="static/img/redes/map.svg" alt="Ubicacion">
                            <p class="texto_icono">concordia 123123</p>
                        </a>
                    </div>
                 

                  
                </div>
              </div>
        
        </section>
{% endblock %}

somosbarro/templates/loginvista.html
<!DOCTYPE html>
<html lang="es">
<head>
	<meta charset="UTF-8">
	<title></title> 
	<meta name="viewport" content="width=device-width, user-scalable=yes, initial-scale=1.0, maximum-scale=3.0, minimum-scale=1.0">
 <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css" >
	<link rel="stylesheet" href="static/css/estilos.css">
	

</head>  
<body>
    <form class="formulario">
    
    <h1>Iniciar sesión</h1>
     <div class="contenedor">
     
     
         
         <div class="input-contenedor">
         <i class="fas fa-envelope icon"></i>
         <input type="text" placeholder="Correo electronico">
         
         </div>
         
         <div class="input-contenedor">
        <i class="fas fa-key icon"></i>
         <input type="password" placeholder="Contraseña">
         
         </div>
         <input type="submit" value="Iniciar sesión" class="button">
         <p>Al registrarte, aceptas nuestras Condiciones de uso y Política de privacidad.</p>
         <p>¿No tienes una cuenta? <a class="link" href="registrarvista.html"> Registrate </a></p>
     </div>
    </form>
</body>
</html>

somosbarro/templates/publicaciones.html
{% extends 'base.html'%}
{% load static %}

{% block contenido %}
       
     <!--seccion publicaciones-->
        
<section class="publicaciones">
    <h2 class="titulo__publicaciones">Publicaciones</h2>

    <div class=" tarjetas row row-cols-1 row-cols-md-3 g-4">
        {% for noticia in todasnoticias %}
        <div class="col">
            <div class="card h-100">
            <img src="{{ noticia.img.url }}" width="300" alt="" class="card-img-top">
            <!--<img src="media/img/noticias/img" width="500" alt="" class="card-img-top">-->
            <div class="card-body">
                <h5 class="card-title">{{ noticia.titulo }}</h5>
                <p class="card-text">{{ noticia.contenido }}.</p>
            </div>
            <div class="card-footer">
                <small class="text-muted">Publicado: {{ noticia.publicado }}</small>
                <p><a class="btn btn-secondary" href="{% url 'noticiasdetalle' id=noticia.id %}">Leer más &raquo;</a></p>
            </div>
            </div>
        </div>
        {% endfor%}
    </div>
</section>


{% endblock %}

somosbarro/templates/quienessomos.html
{% extends 'base.html'%}
{% load static %}
{% block contenido %}
    
        <section class="mision">
            <div class="mision_texto">
                <h1 class="texto">Nuestra Misión</h1>
                <h2>Nuestro principal objetivo es construinos colectivamente a través del Arte, promoviendo políticas de inclusión, ampliando el acceso a la educación.</h2>
            </div>
            
            
            
            <div class="mision_imagen"> 
                <img src="{% static '/img/QuienesSomos-1.jpg'%}" style="width:600px;max-height:600px;" alt="imagen"> 
                    
            </div>
        </section>


        <section class="vision">
            <div class="vision_texto">
                <h1 class="texto">Nuestra Visión</h1>
                <h2>Poder llegar a más niños, que descubran su arte y su pasión, logrando de esta manera tener una experiencia de vida que los enriquezca y contribuya con su crecimento.</h2>
            </div>
    
            <div class="vision_imagen"> 
                <img src="{% static '/img/QuienesSomos-2.jpg'%}" style="width:600px;max-height:600px;" alt="imagen"> 
                    
            </div>
        </section>

        <section class="valores">
            <div class="valores_texto">
                <h1 class="texto">Nuestros valores</h1>
                <h2>Texto de valores</h2>
            </div>
    
            <div class="presentacion_imagen"> 
                <img src="{% static '/img/QuienesSomos-3.jpg'%}" style="width:600px;max-height:4600px00px;"  alt="imagen"> 
                    
            </div>
        </section>
    
        
{% endblock %}
 

somosbarro/templates/registrarvista.html
<!DOCTYPE html>
<html lang="es">
<head>
	<meta charset="UTF-8">
	<title></title> 
	<meta name="viewport" content="width=device-width, user-scalable=yes, initial-scale=1.0, maximum-scale=3.0, minimum-scale=1.0">
 <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css" >
	<link rel="stylesheet" href="static/css/estilos.css">
	

</head>  
<body>
 <form class="formulario">
    
    <h1>Regístrate</h1>
     <div class="contenedor">
     
     <div class="input-contenedor">
         <i class="fas fa-user icon"></i>
         <input type="text" placeholder="Nombre completo">
         
         </div>
         
         <div class="input-contenedor">
         <i class="fas fa-envelope icon"></i>
         <input type="text" placeholder="Correo electronico">
         
         </div>
         
         <div class="input-contenedor">
        <i class="fas fa-key icon"></i>
         <input type="password" placeholder="Contraseña">
         
         </div>
         <input type="submit" value="Registrate" class="button">
         <p>Al registrarte, aceptas nuestras Condiciones de uso y Política de privacidad.</p>
         <p>¿Ya tienes una cuenta?<a class="link" href="loginvista.html"> Iniciar sesión</a></p>
     </div>
    </form>
</body>
</html>